# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bb_log_entry.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bb_log_entry.proto',
  package='berries',
  syntax='proto2',
  serialized_pb=_b('\n\x12\x62\x62_log_entry.proto\x12\x07\x62\x65rries\"\xdc\x01\n\x0c\x62\x62_log_entry\x12\x11\n\ttimestamp\x18\x01 \x02(\r\x12\x10\n\x08pressure\x18\x02 \x01(\x11\x12\x0b\n\x03uvi\x18\x03 \x01(\x11\x12\x0b\n\x03lux\x18\x04 \x01(\x11\x12\n\n\x02rh\x18\x05 \x01(\x11\x12\x13\n\x0btemperature\x18\x06 \x01(\x11\x12\x0f\n\x07\x63ompass\x18\x07 \x03(\x11\x12\x15\n\raccelerometer\x18\x08 \x03(\x11\x12\x0c\n\x04gyro\x18\t \x03(\x11\x12\x12\n\nbattery_mv\x18\x0b \x01(\x11\x12\x10\n\x08gpio0_mv\x18\x0c \x01(\x11\x12\x10\n\x08gpio1_mv\x18\r \x01(\x11')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BB_LOG_ENTRY = _descriptor.Descriptor(
  name='bb_log_entry',
  full_name='berries.bb_log_entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='berries.bb_log_entry.timestamp', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='berries.bb_log_entry.pressure', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uvi', full_name='berries.bb_log_entry.uvi', index=2,
      number=3, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='lux', full_name='berries.bb_log_entry.lux', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rh', full_name='berries.bb_log_entry.rh', index=4,
      number=5, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='berries.bb_log_entry.temperature', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='compass', full_name='berries.bb_log_entry.compass', index=6,
      number=7, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='accelerometer', full_name='berries.bb_log_entry.accelerometer', index=7,
      number=8, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gyro', full_name='berries.bb_log_entry.gyro', index=8,
      number=9, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='battery_mv', full_name='berries.bb_log_entry.battery_mv', index=9,
      number=11, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpio0_mv', full_name='berries.bb_log_entry.gpio0_mv', index=10,
      number=12, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gpio1_mv', full_name='berries.bb_log_entry.gpio1_mv', index=11,
      number=13, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=252,
)

DESCRIPTOR.message_types_by_name['bb_log_entry'] = _BB_LOG_ENTRY

bb_log_entry = _reflection.GeneratedProtocolMessageType('bb_log_entry', (_message.Message,), dict(
  DESCRIPTOR = _BB_LOG_ENTRY,
  __module__ = 'bb_log_entry_pb2'
  # @@protoc_insertion_point(class_scope:berries.bb_log_entry)
  ))
_sym_db.RegisterMessage(bb_log_entry)


# @@protoc_insertion_point(module_scope)
