# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bb_log_entry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x62\x62_log_entry.proto\x12\x07\x62\x65rries\"\x93\x02\n\x0c\x62\x62_log_entry\x12\x11\n\ttimestamp\x18\x01 \x02(\r\x12\x10\n\x08pressure\x18\x02 \x01(\x11\x12\x0b\n\x03uvi\x18\x03 \x01(\x11\x12\x0b\n\x03lux\x18\x04 \x01(\x11\x12\n\n\x02rh\x18\x05 \x01(\x11\x12\x13\n\x0btemperature\x18\x06 \x01(\x11\x12\x0f\n\x07\x63ompass\x18\x07 \x03(\x11\x12\x15\n\raccelerometer\x18\x08 \x03(\x11\x12\x0c\n\x04gyro\x18\t \x03(\x11\x12\x12\n\nbattery_mv\x18\x0b \x01(\x11\x12\x10\n\x08gpio0_mv\x18\x0c \x01(\x11\x12\x10\n\x08gpio1_mv\x18\r \x01(\x11\x12\x11\n\tint_gpio0\x18\x0e \x01(\x08\x12\x11\n\tint_gpio1\x18\x0f \x01(\x08\x12\x0f\n\x07int_acc\x18\x10 \x01(\x08')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bb_log_entry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BB_LOG_ENTRY._serialized_start=32
  _BB_LOG_ENTRY._serialized_end=307
# @@protoc_insertion_point(module_scope)
